blueprint:
  name: My Nudgr Webhook Receiver
  description: Creates a webhook endpoint to receive reminder data from the My Nudgr server and passes it to the processing script.
  domain: automation
  source_url: https://github.com/kenwetech/my-nudgr/blob/main/HA/my-nudgr-automation-blueprint.yaml

  input:
    webhook_id:
      name: Webhook ID
      description: Unique ID used to identify this webhook in Home Assistant.
      default: my_nudgr_webhook
    script_target:
      name: Reminder Processing Script
      description: Select the 'Process Incoming Nudgr' script that will handle the notification logic.
      selector:
        target:
          entity:
            domain: script

trigger:
  - platform: webhook
    webhook_id: !input webhook_id
    allowed_methods:
      - POST
    local_only: true

action:
  - service: script.turn_on
    target: !input script_target
    data:
      variables:
        priority: "{{ trigger.json.priority }}"
        text: "{{ trigger.json.text }}"
        recipient: "{{ trigger.json.recipient }}"
        id: "{{ trigger.json.id }}"
        due_datetime: "{{ trigger.json.due_datetime }}"
        actions: "{{ trigger.json.actions }}"
