blueprint:
  name: My Nudgr Notification Script
  description: |
    Processes reminder data from My Nudgr, sending notifications and TTS alerts based on priority to mapped recipients.
  domain: script
  source_url: https://github.com/kenwetech/my-nudgr/blob/main/HA/my-nudgr-script-blueprint.yaml

  input:
    p1_name:
      name: Recipient 1 Name
      description: 'Enter the exact name that the server will send (e.g., "Jo")'
      selector:
        text:

    p1_devices:
      name: Recipient 1 Notification Targets
      description: The devices or services to notify for Recipient 1.
      selector:
        target:

    p2_name:
      name: Recipient 2 Name
      description: 'Enter the exact name that the server will send (e.g., "Sam")'
      selector:
        text:

    p2_devices:
      name: Recipient 2 Notification Targets
      description: The devices or services to notify for Recipient 2.
      selector:
        target:

    p3_name:
      name: Recipient 3 Name
      description: 'Enter the exact name that the server will send (e.g., "Lex")'
      selector:
        text:

    p3_devices:
      name: Recipient 3 Notification Targets
      description: The devices or services to notify for Recipient 3.
      selector:
        target:

    p4_name:
      name: Recipient 4 Name
      description: 'Enter the exact name that the server will send (e.g., "Ray")'
      selector:
        text:

    p4_devices:
      name: Recipient 4 Notification Targets
      description: The devices or services to notify for Recipient 4.
      selector:
        target:

    default_devices:
      name: Default Devices
      description: Fallback notification targets for unrecognized recipients.
      selector:
        target:

    tts_entity:
      name: TTS Speaker
      description: The media_player entity to use for voice announcements.
      selector:
        entity:
          domain: media_player

mode: parallel
max: 10

fields:
  priority:
    description: The priority of the reminder (1, 2, or 3).
    selector:
      number:
        min: 1
        max: 3
        step: 1
        mode: slider
    example: 1
  text:
    description: The main text of the reminder.
    selector:
      text:
        multiline: true
    example: Take out the trash
  recipient:
    description: 'The intended recipient''s name (e.g., "Sam", "Ray", "default").'
    selector:
      text:
    default: default
    example: Sam
  id:
    description: The unique ID of the reminder for notification tagging.
    selector:
      text:
  actions:
    description: 'A dictionary containing URLs for notification actions.'
    example: '{"nudge": "http://...", "confirm": "http://..."}'
  due_datetime:
    description: The ISO 8601 formatted due date.
    selector:
      datetime:
    example: "2025-06-05T21:30:00-04:00"

sequence:
  - variables:
      lower_recipient: "{{ recipient | lower }}"
      resolved_target: >-
        {% set name_map = {
          (p1_name | lower): p1_devices,
          (p2_name | lower): p2_devices,
          (p3_name | lower): p3_devices,
          (p4_name | lower): p4_devices
        } %}
        {% if lower_recipient in name_map and lower_recipient != "" %}
          {{ name_map[lower_recipient] }}
        {% else %}
          {{ default_devices }}
        {% endif %}
      nudge_url: "{{ actions.nudge if actions is defined and actions.nudge is not none else none }}"
      confirm_url: "{{ actions.confirm if actions is defined and actions.confirm is not none else none }}"
      notification_actions: |
        {% set acts = [] %}
        {% if nudge_url %}
          {% set acts = acts + [{'action': 'URI', 'title': 'Nudge Me Again Later', 'uri': nudge_url}] %}
        {% endif %}
        {% if confirm_url %}
          {% set acts = acts + [{'action': 'URI', 'title': 'Confirm (Stop Alerts)', 'uri': confirm_url}] %}
        {% endif %}
        {{ acts }}

  - choose:
      - conditions:
          - "{{ resolved_target is not none }}"
        sequence:
          - service: notify.notify
            data:
              message: "{{ text }}"
              title: >
                {% if priority == 1 %}🔥 High Priority Reminder
                {% elif priority == 2 %}🔔 Reminder
                {% else %}🧊 Reminder
                {% endif %}
              data:
                tag: "reminder-{{ id }}"
                actions: "{{ notification_actions }}"
                push: >
                  {% if priority == 1 %}
                  { "sound": { "name": "default", "critical": 1, "volume": 1.0 } }
                  {% endif %}
            target: "{{ resolved_target }}"

          - condition: template
            value_template: "{{ tts_entity is not none and tts_entity != 'none' }}"
          - choose:
            - conditions: "{{ priority == 1 }}"
              sequence:
                - service: tts.google_translate_say
                  data:
                    entity_id: !input tts_entity
                    message: "This is a high priority reminder for {{ recipient }}. {{ text }}"
            - conditions: "{{ priority == 2 }}"
              sequence:
                - service: tts.google_translate_say
                  data:
                    entity_id: !input tts_entity
                    message: "Here is a reminder. {{ text }}"

    default:
      - service: system_log.write
        data:
          level: warning
          message: "My Nudgr: Unknown priority '{{ priority }}' or no target for reminder '{{ text }}'."
